export class LineOfCreditMetadata {
    public static value = {
  "structuralTypes": [
    {
      "shortName": "Client",
      "namespace": "Models",
      "autoGeneratedKeyType": "Identity",
      "defaultResourceName": "Client",
      "isComplexType": false,
      "dataProperties": [
        {
          "dataType": "Int32",
          "isPartOfKey": true,
          "isNullable": false,
          "nameOnServer": "ClientId",
          "validators": [{ "name": "required" }, { "name": "int32" }]
        },
        {
          "dataType": "String",
          "isNullable": false,
          "maxLength": 100,
          "nameOnServer": "FirstName",
          "validators": [
            { "name": "required" },
            { "maxLength": 100, "name": "maxLength" }
          ]
        },
        {
          "dataType": "String",
          "isNullable": false,
          "maxLength": 100,
          "nameOnServer": "LastName",
          "validators": [
            { "name": "required" },
            { "maxLength": 100, "name": "maxLength" }
          ]
        },
        {
          "dataType": "Binary",
          "isNullable": true,
          "concurrencyMode": "Fixed",
          "nameOnServer": "Timestamp",
          "validators": []
        }
      ],
      "navigationProperties": [
        {
          "entityTypeName": "LineOfCredit:#Models",
          "isScalar": false,
          "associationName": "Models.LineOfCredit_Models.Client_Client",
          "invForeignKeyNamesOnServer": ["ClientId"],
          "nameOnServer": "LinesOfCredit",
          "validators": []
        }
      ]
    },
    {
      "shortName": "Creditor",
      "namespace": "Models",
      "autoGeneratedKeyType": "Identity",
      "defaultResourceName": "Creditor",
      "isComplexType": false,
      "dataProperties": [
        {
          "dataType": "Int32",
          "isPartOfKey": true,
          "isNullable": false,
          "nameOnServer": "CreditorId",
          "validators": [{ "name": "required" }, { "name": "int32" }]
        },
        {
          "dataType": "String",
          "isNullable": false,
          "maxLength": 100,
          "nameOnServer": "Name",
          "validators": [
            { "name": "required" },
            { "maxLength": 100, "name": "maxLength" }
          ]
        },
        {
          "dataType": "Binary",
          "isNullable": true,
          "concurrencyMode": "Fixed",
          "nameOnServer": "Timestamp",
          "validators": []
        }
      ],
      "navigationProperties": [
        {
          "entityTypeName": "LineOfCredit:#Models",
          "isScalar": false,
          "associationName": "Models.LineOfCredit_Models.Creditor_Creditor",
          "invForeignKeyNamesOnServer": ["CreditorId"],
          "nameOnServer": "LinesOfCredit",
          "validators": []
        }
      ]
    },
    {
      "shortName": "LineOfCredit",
      "namespace": "Models",
      "autoGeneratedKeyType": "Identity",
      "defaultResourceName": "LineOfCredit",
      "isComplexType": false,
      "dataProperties": [
        {
          "dataType": "Int32",
          "isPartOfKey": true,
          "isNullable": false,
          "nameOnServer": "LineOfCreditId",
          "validators": [{ "name": "required" }, { "name": "int32" }]
        },
        {
          "dataType": "Decimal",
          "isNullable": false,
          "nameOnServer": "Balance",
          "validators": [{ "name": "required" }, { "name": "number" }]
        },
        {
          "dataType": "Int32",
          "isNullable": false,
          "nameOnServer": "ClientId",
          "validators": [{ "name": "required" }, { "name": "int32" }]
        },
        {
          "dataType": "Int32",
          "isNullable": false,
          "nameOnServer": "CreditorId",
          "validators": [{ "name": "required" }, { "name": "int32" }]
        },
        {
          "dataType": "Decimal",
          "isNullable": false,
          "nameOnServer": "MinPaymentPercentage",
          "validators": [{ "name": "required" }, { "name": "number" }]
        },
        {
          "dataType": "Binary",
          "isNullable": true,
          "concurrencyMode": "Fixed",
          "nameOnServer": "Timestamp",
          "validators": []
        }
      ],
      "navigationProperties": [
        {
          "entityTypeName": "Client:#Models",
          "isScalar": true,
          "associationName": "Models.LineOfCredit_Models.Client_Client",
          "foreignKeyNamesOnServer": ["ClientId"],
          "nameOnServer": "Client",
          "validators": []
        },
        {
          "entityTypeName": "Creditor:#Models",
          "isScalar": true,
          "associationName": "Models.LineOfCredit_Models.Creditor_Creditor",
          "foreignKeyNamesOnServer": ["CreditorId"],
          "nameOnServer": "Creditor",
          "validators": []
        }
      ]
    }
  ]
};
}